"""Agrega columna nombre_equipo a REQ_EQUIPOS_RED

Revision ID: 1d013660bf76
Revises: b2b18ebb1847
Create Date: 2025-10-01 09:23:23.852592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d013660bf76'
down_revision: Union[str, None] = 'b2b18ebb1847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('REQ_EQUIPOS_RED', sa.Column('nombre_equipo', sa.String(length=20), nullable=True))
    #op.alter_column('REQ_EQUIPOS_RED', 'codigo',
    #           existing_type=sa.VARCHAR(length=25, collation='Modern_Spanish_CI_AS'),
    #           server_default=sa.text("('TCK-' + FORMAT(GETDATE(),'yyyyMM') + '-' + RIGHT('0000' + CAST(NEXT VALUE FOR dbo.seq_req_er AS VARCHAR(10)), 4))"),
    #           existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('REQ_EQUIPOS_RED', 'codigo',
    #           existing_type=sa.VARCHAR(length=25, collation='Modern_Spanish_CI_AS'),
    #           server_default=sa.text("((('TCK-'+format(getdate(),'yyyyMM'))+'-')+right('0000'+CONVERT([varchar](10),NEXT VALUE FOR [dbo].[seq_req_er]),(4)))"),
    #           existing_nullable=False)
    op.drop_column('REQ_EQUIPOS_RED', 'nombre_equipo')
    # ### end Alembic commands ###
