"""Actualizacion de modelos con Base de datos

Revision ID: 2aad890d7e06
Revises: a0c9f49eb7a1
Create Date: 2025-12-03 15:47:24.620131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aad890d7e06'
down_revision: Union[str, None] = 'a0c9f49eb7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('REQ_EQUIPOS_RED', 'usuario',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('REQ_EQUIPOS_RED', 'nombre_equipo',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('REQ_EQUIPOS_RED', 'nombre_equipo',
               existing_type=sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.alter_column('REQ_EQUIPOS_RED', 'usuario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
