"""Se cambio el nombre al campo password

Revision ID: cd37ae08797b
Revises: cb71f4a27dad
Create Date: 2025-12-12 10:40:32.459098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd37ae08797b'
down_revision: Union[str, None] = 'cb71f4a27dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USUARIO_MANTTO', sa.Column('passwordd', sa.String(length=100), nullable=False))
    op.drop_column('USUARIO_MANTTO', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USUARIO_MANTTO', sa.Column('password', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('USUARIO_MANTTO', 'passwordd')
    # ### end Alembic commands ###
